dojoengine/dojo.js

packages/core/package.json
packages/create-burner/package.json
packages/utils/package.json
packages/utils/src/utils/index.ts

no need to add BigInt(keys.length) to compute entity Id

Fix utils getEntityIdFromKeys

---

examples/react-app/src/dojo/createSystemCalls.ts

For compatibility with dojo v0.4.0

fix issue: contract name

---

packages/core/src/provider/DojoProvider.ts

provider docs

---

packages/torii-wasm/crate/Cargo.lock
packages/torii-wasm/crate/Cargo.toml
packages/torii-wasm/crate/src/utils.rs

Fixes u256 format issue with missing "0x", fixes some failing tests
Resolves https://github.com/dojoengine/dojo.js/issues/109

Fix u256 format

---

examples/react/react-app/dojoConfig.ts
examples/react/react-phaser-example/dojoConfig.ts

- Aligns accounts with latest dojo version

fix: account address for dojo 5

---

examples/react/react-app/dojoConfig.ts
examples/react/react-app/package.json
examples/react/react-phaser-example/dojoConfig.ts
examples/react/react-phaser-example/package.json

- fixes config aligned with dojo 0.5.1

fix: config vars

---

packages/core/test/config/config.test.ts
packages/core/test/utils/utils.test.ts
packages/core/tsconfig.json

Closes #113 
Add tests for core

Add core tests

---

packages/core/src/logger/logger.ts
packages/core/src/provider/DojoProvider.ts

Closes #72 
Add logging in DojoProvider

Add logger for Dojo Provider

---

packages/create-burner/src/hooks/useBurnerWindowObject.ts
packages/create-burner/src/hooks/usePredeployedWindowObject.ts

Handle & return error state in`useBurnerWindowObject` & `usePredeployedWindowObject`

fix: handle init error

---

packages/create-dojo/README.md
packages/create-dojo/src/index.ts

fix: create-dojo bug

---

packages/core/package.json

- fixes bug with component generation

fix: component generation

---

examples/node/torii-bot/dojoConfig.ts
examples/react/react-app/dojoConfig.ts
examples/react/react-phaser-example/dojoConfig.ts
examples/react/react-pwa-app/dojoConfig.ts
examples/react/react-threejs/dojoConfig.ts
examples/react/starknet-react-app/dojoConfig.ts
examples/vue/vue-app/dojoConfig.ts

- small change to the manifest path

fix: manifest path

---

examples/react/react-app/src/App.tsx
examples/react/react-app/src/dojo/generated/contractComponents.ts
packages/core/bin/generateComponents.cjs
packages/state/src/recs/index.ts
packages/state/src/utils/index.ts

feat: parses enums as string

---

packages/create-burner/src/manager/burnerManager.ts

add afterDeploying callback to burnerManager
ex:
```
const afterDeploy = async ({ account, deployTx }: { account: Account; deployTx: string }) => {
const receipt = await account!.waitForTransaction(deployTx, {
retryInterval: 200,
});
await tokenFaucet({ account, tokenAddress });
};
burnerManager.setAfterDeployingCallback(afterDeploy);
````

feat: add afterDeploying callback to burnerManager

---

examples/react/react-app/src/dojo/generated/setup.ts
examples/react/react-phaser-example/src/dojo/generated/setup.ts
examples/react/react-pwa-app/src/dojo/generated/setup.ts
examples/react/react-threejs/src/dojo/generated/setup.ts
examples/react/starknet-react-app/src/dojo/generated/setup.ts
examples/vue/vue-app/src/dojo/generated/setup.ts
packages/core/package.json
packages/core/src/utils/index.ts
packages/torii-wasm/crate/Cargo.lock
packages/torii-wasm/crate/Cargo.toml
packages/torii-wasm/crate/src/lib.rs
packages/torii-wasm/crate/src/types.rs
pnpm-lock.yaml

Closes #
- added publishMessage to torii wasm
- added helper method to convert model objects to snip-12 typed data
- exposed publish message through \example
-   [x] Linked relevant issue
-   [x] Updated relevant documentation
-   [x] Added relevant tests
-   [x] Add a dedicated CI job for new examples
-   [x] Performed self-review of the code

feat: relay off chain messages

---

examples/vue/vue-app/package.json
examples/vue/vue-app/src/dojo/generated/setup.ts
pnpm-lock.yaml

…knet version
Closes #
- resolve missing field relayUrl issue 
- upgrade starknet to version 6.1.5
-   [ ] Linked relevant issue
-   [ ] Updated relevant documentation
-   [ ] Added relevant tests
-   [ ] Add a dedicated CI job for new examples
-   [ ] Performed self-review of the code

fixed vue templates bug

---

packages/create-burner/src/manager/burnerManager.ts
packages/create-burner/src/manager/prefundAccount.ts
packages/create-burner/src/types/index.ts

- Add ability to set maxFee while deploying a burner
-   [ ] Linked relevant issue
-   [ ] Updated relevant documentation
-   [ ] Added relevant tests
-   [ ] Add a dedicated CI job for new examples
-   [x] Performed self-review of the code

feat(burners): ability to set maxfee while deploying burner

---

.github/workflows/ci.yaml
examples/react/react-app/package.json
examples/react/react-app/src/App.tsx
examples/react/react-app/src/dojo/generated/contractComponents.ts
packages/state/src/recs/index.ts
packages/state/src/utils/index.ts

fix: bool state bug

---

examples/react/react-phaser-example/package.json
pnpm-lock.yaml

fix: pnpm dep

---

examples/react/react-app/src/dojo/generated/setup.ts
examples/react/react-phaser-example/src/dojo/generated/setup.ts
examples/react/react-pwa-app/src/dojo/generated/setup.ts
examples/react/react-threejs/src/dojo/generated/setup.ts
examples/react/starknet-react-app/src/dojo/generated/setup.ts
examples/vue/vue-app/src/dojo/generated/setup.ts
packages/state/src/recs/index.ts

fix: torii sync

---

packages/create-burner/src/manager/burnerManager.ts

Closes #217
- Skip prefund burners when already deployed
- Readable default prefund value
-   [x] Linked relevant issue
-   [ ] Updated relevant documentation
-   [ ] Added relevant tests
-   [ ] Add a dedicated CI job for new examples
-   [ ] Performed self-review of the code
-   [x] Built packages
-   [x] Built examples

fix: Prefund check

---

.github/workflows/ci.yaml
package.json
packages/create-burner/package.json
packages/torii-wasm/package.json
pnpm-lock.yaml
readme.md
tsup.config.ts

- bumps version
- improves readme

fix: bumps version and readme

---

packages/state/src/utils/index.ts

fix: make bigints bigints in recs

---

packages/state/src/utils/index.ts

fix: types

---

packages/state/src/utils/index.ts

fix: parsing bug

---

.github/workflows/docs.yaml

feat: add docs build:

---

.changeset/lemon-drinks-lie.md
packages/sdk/src/index.ts

feat: export intoEntityKeysClause

---

.changeset/four-singers-stick.md
packages/state/src/recs/index.ts

fix: recs update single component

---

.changeset/cuddly-cities-greet.md
packages/sdk/src/internal/toriiQueryBuilder.ts
packages/sdk/src/web/react/hooks/entities.ts
packages/sdk/src/web/state/index.ts
packages/sdk/src/web/state/zustand.ts

feat: historical zustand
